#!/bin/bash

if [ $# -ne 2 ]
then
  echo "ERROR: a video path and a speed (i.e. 0.25 = 4x speed increase) must be specified as the first and second argument respectively"
  exit 1
fi

# TODO: look into this for including sound: ffmpeg -i DJI_0403.MOV -c:v libx265 -preset slow -x265-params crf=20:no-sao=1:aq-mode=3 -vsync 0 -pix_fmt yuv420p10le DJI_0403.mp4
# ffmpeg -i merge.mp4  -filter_complex "[0:v]setpts=0.05*PTS[v];[0:a]atempo=(1/0.05)[a]" -map "[v]" -map "[a]" fast.mp4

ffmpeg -y -i "$1" -vf "setpts=$2*PTS" -r 60 "$1.speed-adjusted.mp4"
exiftool -extractEmbedded -overwrite_original -TagsFromFile "$1" "$1".speed-adjusted.mp4

echo "Speed adjustment completed"
