#!/bin/bash

if [[ $1 != "--ignore-reqs" ]]; then
    if ! command -v brew &>/dev/null; then
        echo "Python, uv, and ffmpeg are required, but Homebrew is not available for this script to install them"
        echo "You can instead manually install these, then use './install.sh --ignore-reqs'"
        exit 1
    fi
    echo -e "Installing dependencies\n"
    brew install python uv ffmpeg --quiet
    echo -e "\nInstalling video tools\n"
fi

BIN_DIR="/usr/local/bin"
find . -name "*.sh" -o -name "*.py" | while read -r script; do
    script_name=$(basename "$script")
    dest_name="${script_name%.*}"
    cp "$script" "$BIN_DIR/$dest_name"
    chmod +x "$BIN_DIR/$dest_name"
    echo "$dest_name" added to $BIN_DIR
done
